# locator values for login
Browser = chrome
Url = http://orangehrm.qedgetech.com/
obbjUser = //input[@id='txtUsername']
objpass = //input[@id='txtPassword']
objlogin = //input[@id='btnLogin']
objerror = //span[@id='spanMessage']
objAdmin = //b[text()='Admin']
objwelcome = //a[@id = 'welcome']
objlogout = //a[text()='Logout']